#!/usr/bin/env python3
"""
ESI Market Tool - Interactive Setup
A beautiful TUI for configuring the ESI Market Tool
"""

import csv
import os
import sys
import tomllib
import re
from pathlib import Path
from typing import Any

import requests

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text
from rich.prompt import Prompt, Confirm, IntPrompt, FloatPrompt
from rich.rule import Rule
from rich.align import Align
from rich.columns import Columns
from rich.box import ROUNDED, DOUBLE, HEAVY
from rich.style import Style
from rich.theme import Theme
from rich import print as rprint

from gspread.utils import extract_id_from_url

# Custom theme inspired by Claude's color palette
THEME = Theme({
    "title": "bold #D4A574",
    "subtitle": "#B8956E",
    "accent": "#D4A574",
    "success": "bold green",
    "warning": "bold yellow",
    "error": "bold red",
    "info": "dim cyan",
    "hint": "dim #888888",
    "highlight": "bold #D4A574",
    "menu.number": "bold #D4A574",
    "menu.item": "white",
    "menu.desc": "dim",
    "input": "#D4A574",
    "value": "cyan",
    "key": "bold white",
})

console = Console(theme=THEME)

# File paths
CONFIG_FILE = Path("config.toml")
ENV_FILE = Path(".env")
CONFIG_EXAMPLE = Path("config.toml.example")


def clear_screen():
    """Clear terminal screen"""
    console.clear()


def print_header():
    """Print the application header"""
    header_text = Text()
    header_text.append("ESI ", style="bold white")
    header_text.append("Market Tool", style="title")

    subtitle = Text("Interactive Setup", style="subtitle")

    header_panel = Panel(
        Align.center(header_text + Text("\n") + subtitle),
        box=ROUNDED,
        border_style="accent",
        padding=(1, 2),
    )
    console.print(header_panel)
    console.print()


def print_status_bar():
    """Print current configuration status"""
    env_status = "[success]Ready[/]" if ENV_FILE.exists() else "[warning]Not configured[/]"
    config_status = "[success]Ready[/]" if CONFIG_FILE.exists() else "[warning]Missing[/]"

    # Check if .env has required values
    if ENV_FILE.exists():
        env_content = ENV_FILE.read_text()
        if "CLIENT_ID" not in env_content or "your_client_id" in env_content:
            env_status = "[warning]Incomplete[/]"

    status_table = Table(show_header=False, box=None, padding=(0, 2))
    status_table.add_column(justify="center")
    status_table.add_column(justify="center")
    status_table.add_row(
        f"[key]EVE Credentials:[/] {env_status}",
        f"[key]Config:[/] {config_status}",
    )
    console.print(Align.center(status_table))
    console.print()


def load_config() -> dict[str, Any]:
    """Load current configuration from config.toml"""
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE, "rb") as f:
            return tomllib.load(f)
    elif CONFIG_EXAMPLE.exists():
        with open(CONFIG_EXAMPLE, "rb") as f:
            return tomllib.load(f)
    return {}


def save_config(config: dict[str, Any]):
    """Save configuration to config.toml"""
    lines = []
    lines.append("# ESI Market Tool Configuration")
    lines.append("# Generated by setup script")
    lines.append("")

    # ESI section
    lines.append("[esi]")
    lines.append(f"structure_id = {config['esi']['structure_id']}")
    lines.append(f"region_id = {config['esi']['region_id']}")
    lines.append("")

    # User-Agent section
    ua = config.get("user_agent", {})
    lines.append("[user_agent]")
    lines.append(f'app_name = "{ua.get("app_name", "ESI-Market-Tool")}"')
    lines.append(f'app_version = "{ua.get("app_version", "0.2.0")}"')
    lines.append(f'email = "{ua.get("email", "")}"')
    lines.append(f'discord = "{ua.get("discord", "")}"')
    lines.append(f'eve_character = "{ua.get("eve_character", "")}"')
    lines.append(f'source_url = "{ua.get("source_url", "")}"')
    lines.append("")

    # Logging section
    lines.append("[logging]")
    lines.append(f"verbose_console_logging = {'true' if config['logging']['verbose_console_logging'] else 'false'}")
    lines.append("")

    # Rate limiting section
    lines.append("[rate_limiting]")
    lines.append(f"market_orders_wait_time = {config['rate_limiting']['market_orders_wait_time']}")
    lines.append(f"market_history_wait_time = {config['rate_limiting']['market_history_wait_time']}")
    lines.append("")

    # Google Sheets section
    lines.append("[google_sheets]")
    lines.append(f"enabled = {'true' if config['google_sheets']['enabled'] else 'false'}")
    lines.append(f'credentials_file = "{config["google_sheets"]["credentials_file"]}"')
    lines.append(f'workbook_id = "{config["google_sheets"]["workbook_id"]}"')
    lines.append("")
    lines.append("[google_sheets.worksheets]")
    lines.append(f'market_stats = "{config["google_sheets"]["worksheets"]["market_stats"]}"')
    lines.append(f'jita_prices = "{config["google_sheets"]["worksheets"]["jita_prices"]}"')
    lines.append(f'market_history = "{config["google_sheets"]["worksheets"]["market_history"]}"')
    lines.append("")

    # Paths section
    lines.append("[paths]")
    output_dir = config.get("paths", {}).get("output_dir", "output")
    lines.append(f'output_dir = "{output_dir}"')
    lines.append("")
    lines.append("[paths.csv]")
    lines.append(f'market_stats = "{config["paths"]["csv"]["market_stats"]}"')
    lines.append(f'jita_prices = "{config["paths"]["csv"]["jita_prices"]}"')
    lines.append(f'market_history = "{config["paths"]["csv"]["market_history"]}"')
    lines.append("")
    lines.append("[paths.data]")
    lines.append(f'type_ids = "{config["paths"]["data"]["type_ids"]}"')
    lines.append("")

    CONFIG_FILE.write_text("\n".join(lines))


def load_env() -> dict[str, str]:
    """Load current .env file"""
    env_vars = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                # Remove quotes and whitespace
                value = value.strip().strip("'\"")
                env_vars[key.strip()] = value
    return env_vars


def save_env(env_vars: dict[str, str]):
    """Save .env file"""
    lines = [
        "# EVE Online ESI Credentials",
        "# Get these from https://developers.eveonline.com/",
        "",
    ]
    for key, value in env_vars.items():
        lines.append(f"{key} = '{value}'")
    lines.append("")
    ENV_FILE.write_text("\n".join(lines))


def main_menu():
    """Display main menu and handle selection"""
    while True:
        clear_screen()
        print_header()
        print_status_bar()

        menu_items = [
            ("1", "EVE API Credentials", "Set up CLIENT_ID and SECRET_KEY for ESI access"),
            ("2", "ESI Settings", "Configure structure ID and region"),
            ("3", "User-Agent", "Identify your app to CCP (recommended)"),
            ("4", "Type IDs", "Manage tracked item types"),
            ("5", "Rate Limiting", "Adjust request timing to avoid API limits"),
            ("6", "Google Sheets", "Set up automatic spreadsheet updates"),
            ("7", "Logging", "Configure console output verbosity"),
            ("8", "Output Directory", "Set where CSV files are saved"),
            ("9", "View Current Config", "Display all current settings"),
            ("0", "Reset to Defaults", "Restore default configuration"),
            ("q", "Quit(q)", "Exit setup"),
        ]

        menu_table = Table(
            show_header=False,
            box=ROUNDED,
            border_style="accent",
            padding=(0, 1),
            expand=True,
        )
        menu_table.add_column("Key", style="menu.number", width=4, justify="center", highlight=True)
        menu_table.add_column("Option", style="menu.item", width=24)
        menu_table.add_column("Description", style="menu.desc")

        for key, option, desc in menu_items:
            menu_table.add_row(f"[{key}]", option, desc)

        console.print(menu_table)
        console.print()

        choice = Prompt.ask(
            "[accent]Select an option[/] [hint](q to quit)[/]",
            choices=["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "q", "Q"],
            show_choices=False,
        ).lower()

        if choice == "1":
            setup_eve_credentials()
        elif choice == "2":
            setup_esi_settings()
        elif choice == "3":
            setup_user_agent()
        elif choice == "4":
            manage_type_ids()
        elif choice == "5":
            setup_rate_limiting()
        elif choice == "6":
            setup_google_sheets()
        elif choice == "7":
            setup_logging()
        elif choice == "8":
            setup_output_directory()
        elif choice == "9":
            view_config()
        elif choice == "0":
            reset_config()
        elif choice == "q":
            console.print("\n[success]Setup complete![/] Run [highlight]uv run esi_markets.py[/] to start.\n")
            break


def setup_eve_credentials():
    """Set up EVE Online API credentials"""
    clear_screen()
    print_header()

    console.print(Panel(
        "[title]EVE API Credentials Setup[/]\n\n"
        "You need to register an application at the EVE Developer Portal\n"
        "to get your CLIENT_ID and SECRET_KEY.\n\n"
        "[hint]1. Go to [/][link]https://developers.eveonline.com/[/]\n"
        "[hint]2. Click[/] [blue][bold]Create Application[/][/]\n"
        "[hint]3. Add scope:[/] [highlight]esi-markets.structure_markets.v1[/]\n"
        "[hint]4. Set callback URL:[/] [highlight]http://localhost:8000/callback[/]\n"
        "[hint]5. Copy your [/][highlight]Client ID[/] and [highlight]Client Secret below[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    env_vars = load_env()
    current_id = env_vars.get("CLIENT_ID", "")
    current_secret = env_vars.get("SECRET_KEY", "")

    # Show current values (masked)
    if current_id and current_id != "your_client_id":
        console.print(f"[hint]Current CLIENT_ID: {current_id[:8]}...{current_id[-4:]}[/]")
    if current_secret and current_secret != "your_secret_key":
        console.print(f"[hint]Current SECRET_KEY: {'*' * 20}[/]")
    console.print()

    # Get new values
    client_id = Prompt.ask(
        "[key]CLIENT_ID[/]:",
        default=current_id if current_id and current_id != "your_client_id" else "",
    )

    secret_key = Prompt.ask(
        "[key]SECRET_KEY[/]",
        default=current_secret if current_secret and current_secret != "your_secret_key" else "",
        password=True,
    )

    if client_id and secret_key:
        env_vars["CLIENT_ID"] = client_id
        env_vars["SECRET_KEY"] = secret_key
        save_env(env_vars)
        console.print("\n[success]Credentials saved to .env[/]")
    else:
        console.print("\n[warning]No changes made (empty values provided)[/]")

    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def setup_esi_settings():
    """Configure ESI structure and region settings"""
    clear_screen()
    print_header()

    config = load_config()

    console.print(Panel(
        "[title]ESI Settings[/]\n\n"
        "Configure which structure to monitor and which region to query\n"
        "for market history data.\n\n"
        "[hint]Structure ID: The player-owned structure to fetch orders from[/]\n"
        "[info]Common Structure IDs:[/]\n"
        "  [value]1035466617946[/] - 4-HWWF Keepstar\n"
        "  [value]1046831245129[/] - B-9C24 Keepstar\n"

        "[hint]Region ID: The region for market history \n\n"
        "[info]Common Region IDs:[/]\n"
        "  [value]10000002[/] - The Forge (Jita)\n"
        "  [value]10000003[/] - Vale of the Silent\n"
        "  [value]10000043[/] - Domain (Amarr)\n"
        "  [value]10000030[/] - Heimatar (Rens)",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    current_structure = config.get("esi", {}).get("structure_id", 1035466617946)
    current_region = config.get("esi", {}).get("region_id", 10000003)

    console.print(f"[hint]Current Structure ID: [value]{current_structure}[/][/]")
    console.print(f"[hint]Current Region ID: [value]{current_region}[/][/]")
    console.print()

    structure_id = IntPrompt.ask(
        "[key]Structure ID[/]",
        default=current_structure,
    )

    region_id = IntPrompt.ask(
        "[key]Region ID[/]",
        default=current_region,
    )

    config.setdefault("esi", {})
    config["esi"]["structure_id"] = structure_id
    config["esi"]["region_id"] = region_id
    save_config(config)

    console.print("\n[success]ESI settings saved![/]")
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def setup_user_agent():
    """Configure User-Agent header for ESI requests"""
    clear_screen()
    print_header()

    config = load_config()

    console.print(Panel(
        "[title]User-Agent Configuration[/]\n\n"
        "CCP recommends identifying your application in ESI requests.\n"
        "This helps them contact you if there are issues with your app.\n\n"
        "[hint]At minimum, provide a contact email or Discord handle.[/]\n"
        "[hint]All fields are optional but email is strongly recommended.[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    ua = config.get("user_agent", {})

    email = Prompt.ask(
        "[key]Contact Email[/]",
        default=ua.get("email", ""),
    )
    discord = Prompt.ask(
        "[key]Discord Handle[/]",
        default=ua.get("discord", ""),
    )
    eve_character = Prompt.ask(
        "[key]Eve Character Name[/]",
        default=ua.get("eve_character", ""),
    )
    source_url = Prompt.ask(
        "[key]Source URL (e.g. GitHub repo)[/]",
        default=ua.get("source_url", ""),
    )
    app_name = Prompt.ask(
        "[key]App Name[/]",
        default=ua.get("app_name", "ESI-Market-Tool"),
    )
    app_version = Prompt.ask(
        "[key]App Version[/]",
        default=ua.get("app_version", "0.2.0"),
    )

    config.setdefault("user_agent", {})
    config["user_agent"]["app_name"] = app_name
    config["user_agent"]["app_version"] = app_version
    config["user_agent"]["email"] = email
    config["user_agent"]["discord"] = discord
    config["user_agent"]["eve_character"] = eve_character
    config["user_agent"]["source_url"] = source_url
    save_config(config)

    # Show preview
    parts = []
    if email:
        parts.append(email)
    if discord:
        parts.append(f"Discord: {discord}")
    if eve_character:
        parts.append(f"IGN: {eve_character}")
    if source_url:
        parts.append(source_url)
    header = f"{app_name}/{app_version}"
    if parts:
        header += f" ({'; '.join(parts)})"
    console.print(f"\n[hint]User-Agent preview:[/] [value]{header}[/]")

    console.print("\n[success]User-Agent settings saved![/]")
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


# -----------------------------------------------
# Type ID Management
# -----------------------------------------------

TYPE_IDS_FILE = Path("data/type_ids.csv")


def _load_type_ids() -> list[int]:
    """Load current type IDs from the CSV file."""
    if not TYPE_IDS_FILE.exists():
        return []
    with open(TYPE_IDS_FILE, newline="") as f:
        reader = csv.DictReader(f)
        for col in ("type_ids", "type_id", "typeID"):
            if col in (reader.fieldnames or []):
                return [int(row[col]) for row in reader if row[col].strip()]
    return []


def _save_type_ids(ids: list[int]) -> None:
    """Save type IDs to the CSV file."""
    TYPE_IDS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(TYPE_IDS_FILE, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["type_ids"])
        for tid in sorted(set(ids)):
            writer.writerow([tid])


def manage_type_ids():
    """Manage tracked item type IDs"""
    while True:
        clear_screen()
        print_header()

        current_ids = _load_type_ids()
        console.print(Panel(
            "[title]Type ID Management[/]\n\n"
            f"Currently tracking [value]{len(current_ids)}[/] item types.\n\n"
            "[hint]Type IDs determine which items the tool fetches\n"
            "market data for from ESI.[/]",
            box=ROUNDED,
            border_style="info",
        ))
        console.print()

        sub_items = [
            ("1", "View Current Type IDs", "Display all tracked items"),
            ("2", "Search ESI by Name", "Find item type IDs by name"),
            ("3", "Import from CSV", "Load type IDs from a CSV file"),
            ("b", "Back", "Return to main menu"),
        ]

        sub_table = Table(show_header=False, box=ROUNDED, border_style="accent", padding=(0, 1), expand=True)
        sub_table.add_column("Key", style="menu.number", width=4, justify="center")
        sub_table.add_column("Option", style="menu.item", width=24)
        sub_table.add_column("Description", style="menu.desc")
        for key, option, desc in sub_items:
            sub_table.add_row(f"[{key}]", option, desc)

        console.print(sub_table)
        console.print()

        choice = Prompt.ask(
            "[accent]Select an option[/]",
            choices=["1", "2", "3", "b", "B"],
            show_choices=False,
        ).lower()

        if choice == "1":
            _view_type_ids()
        elif choice == "2":
            _search_esi_names()
        elif choice == "3":
            _import_type_ids_csv()
        elif choice == "b":
            break


def _view_type_ids():
    """Display current type IDs in a Rich table"""
    clear_screen()
    print_header()

    ids = _load_type_ids()
    if not ids:
        console.print("[warning]No type IDs found. Import a CSV or search ESI to add items.[/]")
        Prompt.ask("\n[hint]Press Enter to continue[/]", default="")
        return

    # Fetch names for display
    console.print("[hint]Fetching item names from ESI...[/]")
    names = _bulk_resolve_names(ids)

    table = Table(title=f"Tracked Items ({len(ids)})", box=ROUNDED, border_style="accent")
    table.add_column("Type ID", style="value", justify="right")
    table.add_column("Name", style="white")

    for tid in sorted(ids):
        table.add_row(str(tid), names.get(tid, "[hint]Unknown[/]"))

    console.print(table)
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def _bulk_resolve_names(type_ids: list[int]) -> dict[int, str]:
    """Resolve type IDs to names via ESI universe/names endpoint."""
    if not type_ids:
        return {}
    url = "https://esi.evetech.net/latest/universe/names/?datasource=tranquility"
    try:
        # ESI limits POST body to 1000 IDs at a time
        names = {}
        for i in range(0, len(type_ids), 1000):
            batch = type_ids[i:i + 1000]
            resp = requests.post(url, json=batch, headers={"Content-Type": "application/json"})
            resp.raise_for_status()
            for item in resp.json():
                names[item["id"]] = item["name"]
        return names
    except Exception as e:
        console.print(f"[warning]Could not resolve names: {e}[/]")
        return {}


def _search_esi_names():
    """Search ESI for items by name and optionally add to type_ids.csv"""
    clear_screen()
    print_header()

    console.print(Panel(
        "[title]Search ESI for Items[/]\n\n"
        "Enter item names to search for. ESI will return matching IDs.\n"
        "You can then choose which items to add to your tracked list.\n\n"
        "[hint]Separate multiple names with commas.[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    search_input = Prompt.ask("[key]Item name(s)[/]")
    if not search_input.strip():
        return

    names = [n.strip() for n in search_input.split(",") if n.strip()]

    url = "https://esi.evetech.net/latest/universe/ids/?datasource=tranquility&language=en"
    try:
        resp = requests.post(url, json=names, headers={"Content-Type": "application/json"})
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        console.print(f"[error]ESI search failed: {e}[/]")
        Prompt.ask("\n[hint]Press Enter to continue[/]", default="")
        return

    inventory_types = data.get("inventory_types", [])
    if not inventory_types:
        console.print("[warning]No matching items found.[/]")
        Prompt.ask("\n[hint]Press Enter to continue[/]", default="")
        return

    # Display results
    table = Table(title="Search Results", box=ROUNDED, border_style="accent")
    table.add_column("#", style="menu.number", justify="right")
    table.add_column("Type ID", style="value", justify="right")
    table.add_column("Name", style="white")

    for i, item in enumerate(inventory_types, 1):
        table.add_row(str(i), str(item["id"]), item["name"])

    console.print(table)
    console.print()

    if Confirm.ask("[key]Add all found items to tracked type IDs?[/]", default=True):
        current_ids = _load_type_ids()
        new_ids = [item["id"] for item in inventory_types]
        added = [tid for tid in new_ids if tid not in current_ids]
        merged = current_ids + added
        _save_type_ids(merged)
        console.print(f"[success]Added {len(added)} new items ({len(merged)} total tracked).[/]")
    else:
        console.print("[info]No items added.[/]")

    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def _import_type_ids_csv():
    """Import type IDs from an external CSV file"""
    clear_screen()
    print_header()

    console.print(Panel(
        "[title]Import Type IDs from CSV[/]\n\n"
        "Provide the path to a CSV file containing type IDs.\n"
        "The file should have a column named one of:\n"
        "[value]type_ids[/], [value]type_id[/], or [value]typeID[/]\n\n"
        "[hint]You can choose to merge with or replace existing IDs.[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    file_path = Prompt.ask("[key]CSV file path[/]")
    path = Path(file_path).expanduser()

    if not path.exists():
        console.print(f"[error]File not found: {path}[/]")
        Prompt.ask("\n[hint]Press Enter to continue[/]", default="")
        return

    # Read and validate
    try:
        with open(path, newline="") as f:
            reader = csv.DictReader(f)
            col_name = None
            for col in ("type_ids", "type_id", "typeID"):
                if col in (reader.fieldnames or []):
                    col_name = col
                    break

            if not col_name:
                console.print(f"[error]No recognized column (type_ids/type_id/typeID) in {path.name}[/]")
                Prompt.ask("\n[hint]Press Enter to continue[/]", default="")
                return

            import_ids = [int(row[col_name]) for row in reader if row[col_name].strip()]
    except Exception as e:
        console.print(f"[error]Failed to read CSV: {e}[/]")
        Prompt.ask("\n[hint]Press Enter to continue[/]", default="")
        return

    console.print(f"[info]Found {len(import_ids)} type IDs in {path.name}[/]")
    console.print()

    # Preview first 10
    if import_ids:
        preview = import_ids[:10]
        preview_str = ", ".join(str(x) for x in preview)
        if len(import_ids) > 10:
            preview_str += f" ... (+{len(import_ids) - 10} more)"
        console.print(f"[hint]Preview: {preview_str}[/]")
        console.print()

    current_ids = _load_type_ids()
    action = Prompt.ask(
        "[key]Merge with existing or replace?[/]",
        choices=["merge", "replace"],
        default="merge",
    )

    if action == "merge":
        added = [tid for tid in import_ids if tid not in current_ids]
        merged = current_ids + added
        _save_type_ids(merged)
        console.print(f"[success]Merged: {len(added)} new items added ({len(merged)} total).[/]")
    else:
        _save_type_ids(import_ids)
        console.print(f"[success]Replaced: now tracking {len(import_ids)} items.[/]")

    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def setup_rate_limiting():
    """Configure rate limiting settings"""
    clear_screen()
    print_header()

    config = load_config()

    console.print(Panel(
        "[title]Rate Limiting[/]\n\n"
        "Control the delay between ESI API requests to avoid hitting\n"
        "rate limits and getting temporarily banned.\n\n"
        "[hint]Market Orders Wait Time:[/]\n"
        "  Time in seconds between market order page requests.\n"
        "  Recommended: [value]0.1[/] (10 req/sec, limit is ~150 req/sec)\n\n"
        "[hint]Market History Wait Time:[/]\n"
        "  Time in seconds between history requests per item.\n"
        "  Recommended: [value]0.3[/] (~200 req/min, limit is ~300 req/min)\n\n"
        "[warning]Lower values = faster but riskier. Higher = slower but safer.[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    current_orders = config.get("rate_limiting", {}).get("market_orders_wait_time", 0.1)
    current_history = config.get("rate_limiting", {}).get("market_history_wait_time", 0.3)

    orders_wait = FloatPrompt.ask(
        "[key]Market Orders Wait Time (seconds)[/]",
        default=current_orders,
    )

    history_wait = FloatPrompt.ask(
        "[key]Market History Wait Time (seconds)[/]",
        default=current_history,
    )

    config.setdefault("rate_limiting", {})
    config["rate_limiting"]["market_orders_wait_time"] = orders_wait
    config["rate_limiting"]["market_history_wait_time"] = history_wait
    save_config(config)

    console.print("\n[success]Rate limiting settings saved![/]")
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def setup_google_sheets():
    """Configure Google Sheets integration"""
    clear_screen()
    print_header()

    config = load_config()

    console.print(Panel(
        "[title]Google Sheets Integration[/]\n\n"
        "Automatically update a Google Sheets workbook with market data.\n\n"
        "[hint]Setup Requirements:[/]\n"
        "  1. Create a Google Cloud project\n"
        "  2. Enable Google Sheets API and Google Drive API\n"
        "  3. Create a service account and download JSON credentials\n"
        "  4. Share your spreadsheet with the service account email\n\n"
        "[info]See README.md for detailed setup instructions[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    gs_config = config.get("google_sheets", {})
    current_enabled = gs_config.get("enabled", False)
    current_creds = gs_config.get("credentials_file", "google_credentials.json")
    current_workbook = gs_config.get("workbook_id", "")

    console.print(f"[hint]Currently: [value]{'Enabled' if current_enabled else 'Disabled'}[/][/]")
    console.print()

    enabled = Confirm.ask(
        "[key]Enable Google Sheets integration?[/]",
        default=current_enabled,
    )

    if enabled:
        console.print()
        console.print("[hint]The credentials file should be in your project directory.[/]")
        creds_file = Prompt.ask(
            "[key]Credentials JSON file[/]",
            default=current_creds,
        )

        # Check if file exists
        if not Path(creds_file).exists():
            console.print(f"[warning]Warning: {creds_file} not found. Make sure to add it![/]")

        console.print()
        console.print("[hint]Get the workbook ID from your spreadsheet URL:[/]")
        console.print("[hint]https://docs.google.com/spreadsheets/d/[value]<WORKBOOK_ID>[/]/edit[/]")
        workbook_url = Prompt.ask(
            "[key]Workbook ID[/]",
            default=current_workbook,
        )
        workbook_id = extract_id_from_url(workbook_url)

        config.setdefault("google_sheets", {})
        config["google_sheets"]["enabled"] = True
        config["google_sheets"]["credentials_file"] = creds_file
        config["google_sheets"]["workbook_id"] = workbook_id
    else:
        config.setdefault("google_sheets", {})
        config["google_sheets"]["enabled"] = False

    save_config(config)

    console.print("\n[success]Google Sheets settings saved![/]")
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def setup_logging():
    """Configure logging settings"""
    clear_screen()
    print_header()

    config = load_config()

    console.print(Panel(
        "[title]Logging Settings[/]\n\n"
        "Control how much information is displayed during execution.\n\n"
        "[hint]Verbose Console Logging:[/]\n"
        "  [value]Enabled[/]  - Show detailed progress (INFO level)\n"
        "  [value]Disabled[/] - Show only warnings and errors\n\n"
        "[info]Log files are always created in the logs/ directory[/]\n"
        "[info]regardless of this setting.[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    current_verbose = config.get("logging", {}).get("verbose_console_logging", True)

    verbose = Confirm.ask(
        "[key]Enable verbose console logging?[/]",
        default=current_verbose,
    )

    config.setdefault("logging", {})
    config["logging"]["verbose_console_logging"] = verbose
    save_config(config)

    console.print("\n[success]Logging settings saved![/]")
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def setup_output_directory():
    """Configure output directory"""
    clear_screen()
    print_header()

    config = load_config()

    console.print(Panel(
        "[title]Output Directory[/]\n\n"
        "Configure where CSV output files are saved.\n\n"
        "[hint]Default:[/] [value]output[/] (relative to project root)\n\n"
        "[info]Supports absolute paths and ~ for home directory.[/]\n"
        "[info]Also configurable via CLI: --output-dir /path/to/dir[/]",
        box=ROUNDED,
        border_style="info",
    ))
    console.print()

    current_dir = config.get("paths", {}).get("output_dir", "output")
    console.print(f"[hint]Current output directory: [value]{current_dir}[/][/]")
    console.print()

    output_dir = Prompt.ask(
        "[key]Output Directory[/]",
        default=current_dir,
    )

    config.setdefault("paths", {})
    config["paths"]["output_dir"] = output_dir
    save_config(config)

    console.print("\n[success]Output directory saved![/]")
    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def view_config():
    """Display current configuration"""
    clear_screen()
    print_header()

    config = load_config()
    env_vars = load_env()

    # EVE Credentials
    console.print(Rule("[title]EVE API Credentials[/]", style="accent"))
    creds_table = Table(show_header=False, box=None, padding=(0, 2))
    creds_table.add_column("Key", style="key")
    creds_table.add_column("Value", style="value")

    client_id = env_vars.get("CLIENT_ID", "Not set")
    secret_key = env_vars.get("SECRET_KEY", "")

    if client_id and client_id != "your_client_id" and client_id != "Not set":
        client_id = f"{client_id[:8]}...{client_id[-4:]}"
    if secret_key and secret_key != "your_secret_key":
        secret_key = "*" * 20
    else:
        secret_key = "Not set"

    creds_table.add_row("CLIENT_ID", client_id)
    creds_table.add_row("SECRET_KEY", secret_key)
    console.print(creds_table)
    console.print()

    # ESI Settings
    console.print(Rule("[title]ESI Settings[/]", style="accent"))
    esi_table = Table(show_header=False, box=None, padding=(0, 2))
    esi_table.add_column("Key", style="key")
    esi_table.add_column("Value", style="value")
    esi_table.add_row("Structure ID", str(config.get("esi", {}).get("structure_id", "Not set")))
    esi_table.add_row("Region ID", str(config.get("esi", {}).get("region_id", "Not set")))
    console.print(esi_table)
    console.print()

    # User-Agent
    console.print(Rule("[title]User-Agent[/]", style="accent"))
    ua = config.get("user_agent", {})
    ua_table = Table(show_header=False, box=None, padding=(0, 2))
    ua_table.add_column("Key", style="key")
    ua_table.add_column("Value", style="value")
    ua_table.add_row("App Name", ua.get("app_name", "ESI-Market-Tool"))
    ua_table.add_row("Version", ua.get("app_version", "0.2.0"))
    ua_table.add_row("Email", ua.get("email", "") or "[hint]Not set[/]")
    ua_table.add_row("Discord", ua.get("discord", "") or "[hint]Not set[/]")
    ua_table.add_row("Eve Character", ua.get("eve_character", "") or "[hint]Not set[/]")
    ua_table.add_row("Source URL", ua.get("source_url", "") or "[hint]Not set[/]")
    console.print(ua_table)
    console.print()

    # Rate Limiting
    console.print(Rule("[title]Rate Limiting[/]", style="accent"))
    rate_table = Table(show_header=False, box=None, padding=(0, 2))
    rate_table.add_column("Key", style="key")
    rate_table.add_column("Value", style="value")
    rate_table.add_row(
        "Market Orders Wait",
        f"{config.get('rate_limiting', {}).get('market_orders_wait_time', 0.1)}s"
    )
    rate_table.add_row(
        "Market History Wait",
        f"{config.get('rate_limiting', {}).get('market_history_wait_time', 0.3)}s"
    )
    console.print(rate_table)
    console.print()

    # Google Sheets
    console.print(Rule("[title]Google Sheets[/]", style="accent"))
    gs_table = Table(show_header=False, box=None, padding=(0, 2))
    gs_table.add_column("Key", style="key")
    gs_table.add_column("Value", style="value")

    gs_enabled = config.get("google_sheets", {}).get("enabled", False)
    gs_table.add_row("Enabled", "[success]Yes[/]" if gs_enabled else "[hint]No[/]")
    gs_table.add_row("Credentials File", config.get("google_sheets", {}).get("credentials_file", ""))

    workbook_id = config.get("google_sheets", {}).get("workbook_id", "")
    if workbook_id:
        gs_table.add_row("Workbook ID", f"{workbook_id[:15]}..." if len(workbook_id) > 15 else workbook_id)
    else:
        gs_table.add_row("Workbook ID", "[hint]Not set[/]")
    console.print(gs_table)
    console.print()

    # Logging
    console.print(Rule("[title]Logging[/]", style="accent"))
    log_table = Table(show_header=False, box=None, padding=(0, 2))
    log_table.add_column("Key", style="key")
    log_table.add_column("Value", style="value")
    log_table.add_row(
        "Verbose Console",
        "[success]Yes[/]" if config.get("logging", {}).get("verbose_console_logging", True) else "[hint]No[/]"
    )
    console.print(log_table)

    console.print()
    Prompt.ask("[hint]Press Enter to continue[/]", default="")


def reset_config():
    """Reset configuration to defaults"""
    clear_screen()
    print_header()

    console.print(Panel(
        "[warning]Reset Configuration[/]\n\n"
        "This will reset config.toml to default values.\n"
        "Your .env credentials will NOT be affected.\n\n"
        "[error]This action cannot be undone![/]",
        box=ROUNDED,
        border_style="warning",
    ))
    console.print()

    if Confirm.ask("[warning]Are you sure you want to reset?[/]", default=False):
        if CONFIG_EXAMPLE.exists():
            # Copy from example
            import shutil
            shutil.copy(CONFIG_EXAMPLE, CONFIG_FILE)
            console.print("\n[success]Configuration reset to defaults![/]")
        else:
            console.print("\n[error]config.toml.example not found![/]")
    else:
        console.print("\n[info]Reset cancelled.[/]")

    Prompt.ask("\n[hint]Press Enter to continue[/]", default="")


def check_setup_needed() -> bool:
    """Check if initial setup is needed"""
    if not CONFIG_FILE.exists():
        return True
    if not ENV_FILE.exists():
        return True

    env_vars = load_env()
    if not env_vars.get("CLIENT_ID") or env_vars.get("CLIENT_ID") == "your_client_id":
        return True
    if not env_vars.get("SECRET_KEY") or env_vars.get("SECRET_KEY") == "your_secret_key":
        return True

    return False


def show_welcome():
    """Show welcome screen for first-time setup"""
    clear_screen()

    welcome_text = Text()
    welcome_text.append("\n")
    welcome_text.append("Welcome to ", style="white")
    welcome_text.append("ESI Market Tool", style="title")
    welcome_text.append("\n\n", style="white")
    welcome_text.append("This setup wizard will help you configure the tool\n", style="hint")
    welcome_text.append("for fetching Eve Online market data.\n\n", style="hint")
    welcome_text.append("You'll need:\n", style="white")
    welcome_text.append("  - Eve Developer Portal account\n", style="hint")
    welcome_text.append("  - CLIENT_ID and SECRET_KEY from your ESI app\n", style="hint")
    welcome_text.append("  - (Optional) Google Cloud credentials for Sheets\n", style="hint")

    console.print(Panel(
        Align.center(welcome_text),
        box=DOUBLE,
        border_style="accent",
        padding=(1, 4),
    ))
    console.print()

    Prompt.ask("[accent]Press Enter to begin setup[/]", default="")


def main():
    """Main entry point"""
    try:
        # Check if this is first run
        if check_setup_needed():
            show_welcome()

        main_menu()

    except KeyboardInterrupt:
        console.print("\n\n[hint]Setup cancelled.[/]")
        sys.exit(0)
    except Exception as e:
        console.print(f"\n[error]Error: {e}[/]")
        sys.exit(1)


if __name__ == "__main__":
    main()
